//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsaGappsTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WsaGappsTool.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../tools/7z/7z.exe.
        /// </summary>
        internal static string _7zipExe {
            get {
                return ResourceManager.GetString("_7zipExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache/.
        /// </summary>
        internal static string CacheDirectory {
            get {
                return ResourceManager.GetString("CacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../qemu/qemu-system-x86_64.exe.
        /// </summary>
        internal static string QemuExe {
            get {
                return ResourceManager.GetString("QemuExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache/temp/.
        /// </summary>
        internal static string VHDX_Contents_TempDir {
            get {
                return ResourceManager.GetString("VHDX_Contents_TempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache/temp/gapps/.
        /// </summary>
        internal static string VHDX_Contents_TempDir_Gapps {
            get {
                return ResourceManager.GetString("VHDX_Contents_TempDir_Gapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache/temp/images/.
        /// </summary>
        internal static string VHDX_Contents_TempDir_Images {
            get {
                return ResourceManager.GetString("VHDX_Contents_TempDir_Images", resourceCulture);
            }
        }
    }
}
